jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - sonarcloud/scan
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3
version: 2.1
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
