# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1
orbs: 
  sonarcloud: extendaretail/sonarcloud@0.0.2
job:
  check_quality_gate:
    docker:
    - image: 'cimg/base:stable'
    steps:
      - checkout
      - sonarcloud/check_quality_gate

workflows:
  main:
    jobs:
      - sonarcloud/check_quality_gate:
          context: SonarCloud
