# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1
orbs: 
  sonarcloud: extendaretail/sonarcloud@0.0.2
job:
  sonarscan:
    docker:
    - image: 'cimg/base:stable'
    steps:
      - checkout          
      - run:
          name: Download and unzip the SonarScanner
          command: |
            echo "export SONAR_SCANNER_VERSION=4.4.0.2170" >> $BASH_ENV
            source $BASH_ENV
            echo "export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux" >> $BASH_ENV
            source $BASH_ENV
            curl --create-dirs -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
            unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
            echo "export PATH=$SONAR_SCANNER_HOME/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            echo "export SONAR_SCANNER_OPTS='-server'" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Execute the SonarScanner
          # command: ./sonar_run.sh
          command: |
            sonar-scanner \
            -Dsonar.organization=giulio-giunta \
            -Dsonar.projectKey=web-sonar \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.python.version=3.9 \
            -Dsonar.login=${SONAR_TOKEN}
  check_quality_gate:
    steps:
      - checkout
      - sonarcloud/check_quality_gate

workflows:
  main:
    jobs:
      - sonarcloud/check_quality_gate:
          context: SonarCloud
